///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexWebSampleProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FillRanorexSoftwareDownloadForm recording.
    /// </summary>
    [TestModule("4ecad458-00b3-4f5e-b275-244c5f122c11", ModuleType.Recording, 1)]
    public partial class FillRanorexSoftwareDownloadForm : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexWebSampleProjectRepository repository.
        /// </summary>
        public static RanorexWebSampleProjectRepository repo = RanorexWebSampleProjectRepository.Instance;

        static FillRanorexSoftwareDownloadForm instance = new FillRanorexSoftwareDownloadForm();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FillRanorexSoftwareDownloadForm()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FillRanorexSoftwareDownloadForm Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // To define a script for downloading ranorex software form
            Report.Log(ReportLevel.Info, "Section", "To define a script for downloading ranorex software form", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.RanorexForm.FirstName' at Center.", repo.ApplicationUnderTest.RanorexForm.FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RanorexForm.FirstName.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RanorexForm.FirstName' at 127;28.", repo.ApplicationUnderTest.RanorexForm.FirstNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RanorexForm.FirstName.Click("127;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'student' with focus on 'ApplicationUnderTest.RanorexForm.FirstName'.", repo.ApplicationUnderTest.RanorexForm.FirstNameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RanorexForm.FirstName.PressKeys("student");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.RanorexForm.FirstName'.", repo.ApplicationUnderTest.RanorexForm.FirstNameInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RanorexForm.FirstName.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RanorexForm.LastName' at 23;30.", repo.ApplicationUnderTest.RanorexForm.LastNameInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RanorexForm.LastName.Click("23;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'gupta' with focus on 'ApplicationUnderTest.RanorexForm.LastName'.", repo.ApplicationUnderTest.RanorexForm.LastNameInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RanorexForm.LastName.PressKeys("gupta");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.RanorexForm.LastName'.", repo.ApplicationUnderTest.RanorexForm.LastNameInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.RanorexForm.LastName.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RanorexForm.Email' at 249;14.", repo.ApplicationUnderTest.RanorexForm.EmailInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.RanorexForm.Email.Click("249;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'a@automationpractice.com' with focus on 'ApplicationUnderTest.RanorexForm.Email'.", repo.ApplicationUnderTest.RanorexForm.EmailInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.RanorexForm.Email.PressKeys("a@automationpractice.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.RanorexForm.Email'.", repo.ApplicationUnderTest.RanorexForm.EmailInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.RanorexForm.Email.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RanorexForm.Company' at 250;18.", repo.ApplicationUnderTest.RanorexForm.CompanyInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.RanorexForm.Company.Click("250;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'student' with focus on 'ApplicationUnderTest.RanorexForm.Company'.", repo.ApplicationUnderTest.RanorexForm.CompanyInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.RanorexForm.Company.PressKeys("student");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.RanorexForm.Company'.", repo.ApplicationUnderTest.RanorexForm.CompanyInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.RanorexForm.Company.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RanorexForm.BusPhone' at 196;36.", repo.ApplicationUnderTest.RanorexForm.BusPhoneInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.RanorexForm.BusPhone.Click("196;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9876543210' with focus on 'ApplicationUnderTest.RanorexForm.BusPhone'.", repo.ApplicationUnderTest.RanorexForm.BusPhoneInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.RanorexForm.BusPhone.PressKeys("9876543210");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.RanorexForm.BusPhone'.", repo.ApplicationUnderTest.RanorexForm.BusPhoneInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.RanorexForm.BusPhone.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RanorexForm.JobTitle' at 155;39.", repo.ApplicationUnderTest.RanorexForm.JobTitleInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.RanorexForm.JobTitle.Click("155;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'student' with focus on 'ApplicationUnderTest.RanorexForm.JobTitle'.", repo.ApplicationUnderTest.RanorexForm.JobTitleInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.RanorexForm.JobTitle.PressKeys("student");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(19));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.RanorexForm.JobTitle'.", repo.ApplicationUnderTest.RanorexForm.JobTitleInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.RanorexForm.JobTitle.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'Education' on item 'ApplicationUnderTest.RanorexForm.Industry'.", repo.ApplicationUnderTest.RanorexForm.IndustryInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.RanorexForm.Industry.Element.SetAttributeValue("TagValue", "Education");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(22));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.RanorexForm.Industry'.", repo.ApplicationUnderTest.RanorexForm.IndustryInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.RanorexForm.Industry.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '0' on item 'ApplicationUnderTest.RanorexForm.DropdownMenu2'.", repo.ApplicationUnderTest.RanorexForm.DropdownMenu2Info, new RecordItemIndex(24));
            repo.ApplicationUnderTest.RanorexForm.DropdownMenu2.Element.SetAttributeValue("TagValue", "0");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(25));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to 'IN' on item 'ApplicationUnderTest.Country'.", repo.ApplicationUnderTest.CountryInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.Country.Element.SetAttributeValue("TagValue", "IN");
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'ApplicationUnderTest.Country'.", repo.ApplicationUnderTest.CountryInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.Country.PressKeys("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(28));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'ApplicationUnderTest.RanorexForm.Submit'.", repo.ApplicationUnderTest.RanorexForm.SubmitInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.RanorexForm.Submit.PerformClick();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RanorexForm.Submit' at 84;30.", repo.ApplicationUnderTest.RanorexForm.SubmitInfo, new RecordItemIndex(30));
            //repo.ApplicationUnderTest.RanorexForm.Submit.Click("84;30");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 7s.", new RecordItemIndex(31));
            Delay.Duration(7000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
