///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexWebSampleProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexWebSampleProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a85f5746-055d-4269-a0e1-c10dcacb3922")]
    public partial class RanorexWebSampleProjectRepository : RepoGenBaseFolder
    {
        static RanorexWebSampleProjectRepository instance = new RanorexWebSampleProjectRepository();
        RanorexWebSampleProjectRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexWebSampleProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("a85f5746-055d-4269-a0e1-c10dcacb3922")]
        public static RanorexWebSampleProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexWebSampleProjectRepository() 
            : base("RanorexWebSampleProjectRepository", "/", null, 0, false, "a85f5746-055d-4269-a0e1-c10dcacb3922", ".\\RepositoryImages\\RanorexWebSampleProjectRepositorya85f5746.rximgres")
        {
            _applicationundertest = new RanorexWebSampleProjectRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a85f5746-055d-4269-a0e1-c10dcacb3922")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("8b59c128-29bc-4331-b2c9-38267a21c8fc")]
        public virtual RanorexWebSampleProjectRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexWebSampleProjectRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("8b59c128-29bc-4331-b2c9-38267a21c8fc")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RanorexWebSampleProjectRepositoryFolders.RanorexFormFolder _ranorexform;
            RepoItemInfo _countryInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "8b59c128-29bc-4331-b2c9-38267a21c8fc", "")
            {
                _ranorexform = new RanorexWebSampleProjectRepositoryFolders.RanorexFormFolder(this);
                _countryInfo = new RepoItemInfo(this, "Country", ".//select[#'country']", ".//select[#'country']", 30000, null, "f1995c12-6540-4eb4-a4be-a24fbc154ff8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8b59c128-29bc-4331-b2c9-38267a21c8fc")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8b59c128-29bc-4331-b2c9-38267a21c8fc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Country item.
            /// </summary>
            [RepositoryItem("f1995c12-6540-4eb4-a4be-a24fbc154ff8")]
            public virtual Ranorex.SelectTag Country
            {
                get
                {
                    return _countryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Country item info.
            /// </summary>
            [RepositoryItemInfo("f1995c12-6540-4eb4-a4be-a24fbc154ff8")]
            public virtual RepoItemInfo CountryInfo
            {
                get
                {
                    return _countryInfo;
                }
            }

            /// <summary>
            /// The RanorexForm folder.
            /// </summary>
            [RepositoryFolder("7e27c9c1-7b73-44d2-9f44-af77a28d7aca")]
            public virtual RanorexWebSampleProjectRepositoryFolders.RanorexFormFolder RanorexForm
            {
                get { return _ranorexform; }
            }
        }

        /// <summary>
        /// The RanorexFormFolder folder.
        /// </summary>
        [RepositoryFolder("7e27c9c1-7b73-44d2-9f44-af77a28d7aca")]
        public partial class RanorexFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _companyInfo;
            RepoItemInfo _busphoneInfo;
            RepoItemInfo _jobtitleInfo;
            RepoItemInfo _industryInfo;
            RepoItemInfo _dropdownmenu2Info;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new RanorexForm  folder.
            /// </summary>
            public RanorexFormFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexForm", ".//div[#'et_builder_outer_content']//form[@name='RNRX-Free-Download']", parentFolder, 30000, null, false, "7e27c9c1-7b73-44d2-9f44-af77a28d7aca", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//inputtag[@name='FirstName']", "", 30000, null, "680824f4-00a6-4ffe-990b-0b3420466b2e");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//inputtag[@name='LastName']", "", 30000, null, "1a849529-d7b6-40c7-86c7-c11588109dd7");
                _emailInfo = new RepoItemInfo(this, "Email", ".//inputtag[@name='Email']", "", 30000, null, "a206afa3-dca4-4e53-a03c-0a3039df138a");
                _companyInfo = new RepoItemInfo(this, "Company", ".//inputtag[@name='Company']", "div[3]/div/div[1]/div[2]//form[@name='RNRX-Free-Download']", 30000, null, "316cb751-d1f0-4e35-a03b-f6aa6cbce267");
                _busphoneInfo = new RepoItemInfo(this, "BusPhone", ".//inputtag[@name='busPhone']", "div[3]/div/div[1]/div[2]//form[@name='RNRX-Free-Download']", 30000, null, "4b482ce7-21c3-457e-8b70-3d6111cc2267");
                _jobtitleInfo = new RepoItemInfo(this, "JobTitle", ".//p/inputtag[@name='JobTitle']", "div[3]/div/div[1]/div[2]//form[@name='RNRX-Free-Download']", 30000, null, "fc073af1-d4b8-4669-b9b1-de4ef3eac155");
                _industryInfo = new RepoItemInfo(this, "Industry", ".//select[@name='Industry']", "div[3]/div/div[1]/div[2]//form[@name='RNRX-Free-Download']", 30000, null, "f6122c8b-492d-4bfc-8827-bcc5715a874c");
                _dropdownmenu2Info = new RepoItemInfo(this, "DropdownMenu2", ".//select[@name='dropdownMenu2']", "div[3]/div/div[1]/div[2]//form[@name='RNRX-Free-Download']", 30000, null, "c00aaf39-8265-4fe4-87e5-db60f2420b8b");
                _submitInfo = new RepoItemInfo(this, "Submit", "p/input[@type='submit']", "", 30000, null, "36836a9d-c58b-4c3b-966b-0641cd139617");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7e27c9c1-7b73-44d2-9f44-af77a28d7aca")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7e27c9c1-7b73-44d2-9f44-af77a28d7aca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("680824f4-00a6-4ffe-990b-0b3420466b2e")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("680824f4-00a6-4ffe-990b-0b3420466b2e")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("1a849529-d7b6-40c7-86c7-c11588109dd7")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("1a849529-d7b6-40c7-86c7-c11588109dd7")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("a206afa3-dca4-4e53-a03c-0a3039df138a")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("a206afa3-dca4-4e53-a03c-0a3039df138a")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Company item.
            /// </summary>
            [RepositoryItem("316cb751-d1f0-4e35-a03b-f6aa6cbce267")]
            public virtual Ranorex.InputTag Company
            {
                get
                {
                    return _companyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Company item info.
            /// </summary>
            [RepositoryItemInfo("316cb751-d1f0-4e35-a03b-f6aa6cbce267")]
            public virtual RepoItemInfo CompanyInfo
            {
                get
                {
                    return _companyInfo;
                }
            }

            /// <summary>
            /// The BusPhone item.
            /// </summary>
            [RepositoryItem("4b482ce7-21c3-457e-8b70-3d6111cc2267")]
            public virtual Ranorex.InputTag BusPhone
            {
                get
                {
                    return _busphoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BusPhone item info.
            /// </summary>
            [RepositoryItemInfo("4b482ce7-21c3-457e-8b70-3d6111cc2267")]
            public virtual RepoItemInfo BusPhoneInfo
            {
                get
                {
                    return _busphoneInfo;
                }
            }

            /// <summary>
            /// The JobTitle item.
            /// </summary>
            [RepositoryItem("fc073af1-d4b8-4669-b9b1-de4ef3eac155")]
            public virtual Ranorex.InputTag JobTitle
            {
                get
                {
                    return _jobtitleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The JobTitle item info.
            /// </summary>
            [RepositoryItemInfo("fc073af1-d4b8-4669-b9b1-de4ef3eac155")]
            public virtual RepoItemInfo JobTitleInfo
            {
                get
                {
                    return _jobtitleInfo;
                }
            }

            /// <summary>
            /// The Industry item.
            /// </summary>
            [RepositoryItem("f6122c8b-492d-4bfc-8827-bcc5715a874c")]
            public virtual Ranorex.SelectTag Industry
            {
                get
                {
                    return _industryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Industry item info.
            /// </summary>
            [RepositoryItemInfo("f6122c8b-492d-4bfc-8827-bcc5715a874c")]
            public virtual RepoItemInfo IndustryInfo
            {
                get
                {
                    return _industryInfo;
                }
            }

            /// <summary>
            /// The DropdownMenu2 item.
            /// </summary>
            [RepositoryItem("c00aaf39-8265-4fe4-87e5-db60f2420b8b")]
            public virtual Ranorex.SelectTag DropdownMenu2
            {
                get
                {
                    return _dropdownmenu2Info.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The DropdownMenu2 item info.
            /// </summary>
            [RepositoryItemInfo("c00aaf39-8265-4fe4-87e5-db60f2420b8b")]
            public virtual RepoItemInfo DropdownMenu2Info
            {
                get
                {
                    return _dropdownmenu2Info;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("36836a9d-c58b-4c3b-966b-0641cd139617")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("36836a9d-c58b-4c3b-966b-0641cd139617")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
